version: '3.4'

services:
  shop.api:
    image: ${DOCKER_REGISTRY}ShopApi
    build:
      context: .
      dockerfile: Shop.Core/Shop.Api/Dockerfile
    depends_on:
      - sql.data

  shop.parsers.samsonopt:
    image: ${DOCKER_REGISTRY}Shop.Parsers.SamsonOpt
    build:
      context: .
      dockerfile: Shop.Parsers/Shop.Parsers.Samson/Shop.Parsers.SamsonOpt/Dockerfile

###### using single instance of postgres in development 
  sql.data:
    image: postgres
